A bunch of stuff
GenerateApps/GenerateClient pull request #10
Opened 2023-06-24 05:18 UTC by SpookyKipper

1. I beautified the code a bit using a tool but it should still work

2. Added `showRedirect($domain)`
3. Moved `tableToArray($html)` out
4. Improved `getUserStats($option)`
   - The ability to get individual statistics item
   - Remove the random numebrs/elements that VistaPanel has for some reason

2023-06-24 13:19 UTC, greenreader9 reviewed
Honestly, looks good to me. As long as it works!

2023-06-24 13:35 UTC, 4yx reviewed
I can't say I disapprove, especially with the simpleCurl beautifications, and if it works well.

I am curious, however, about some oddities:
In line 192, the array is converted to ``["submit" => true]``. However, in line 283, it goes and does:
```php
[
                "db" => $dbname,
]
```
Instead of an one-line ``["db" => $dbname]``.

There are also some places where I'm not sure beautificiation was needed/may add unnecessary lines (like the login function parameters, or the cookie setting in login, or lines 566-571), but if you intend to use this tool from now on, changing them manually would be pointless.

2023-06-24 14:39 UTC, SpookyKipper commented
> ```
> [
>                 "db" => $dbname,
> ]
> ```
> 
> Instead of an one-line `["db" => $dbname]`.

It seems that it's because it follows if the previous `array(variable)` is a single line or multi-line.


> There are also some places where I'm not sure beautificiation was needed/may add unnecessary lines (like the login function parameters, or the cookie setting in login, or lines 566-571), but if you intend to use this tool from now on, changing them manually would be pointless.

Perhaps it got confused because we skip lines for like 1 or 2 strings and not having a specific pattern

2023-06-24 15:29 UTC, 4yx approved these changes
Hmm, okay. See if it's easy to fix those (and if you believe they should be fixed, of course), otherwise everything looks good to me as well.

2023-06-25 03:42 UTC, SpookyKipper commented
I actually don't mind if it's fixed or not, since it won't make a big difference.

2023-06-25 04:54 UTC, ImLoadingUuU commented
Cool. i know random numbers problem in vista panel. but idk how to fix that.

2023-06-25 15:07 UTC, 4yx commented
> I actually don't mind if it's fixed or not, since it won't make a big difference.

Planning to merge it then?

2023-06-27 00:58 UTC, greenreader9 requested changes
Readability, prevent 🙄 when viewing

2023-06-27 00:58 UTC, greenreader9 commented on api-client.php
> +            true,
Lines 283-285 should be combined to one

2023-06-27 00:58 UTC, greenreader9 commented on api-client.php
> +                str_replace(
300-303 can probably be combined for readability, no?

2023-06-27 00:58 UTC, greenreader9 commented on api-client.php
> +            [
Combine 610-612

2023-06-27 00:58 UTC, greenreader9 commented on api-client.php
> +            [
Combine 675-677

2023-06-28 08:43 UTC, SpookyKipper commented
These commits should do.

2023-07-06 10:58 UTC, SpookyKipper commented
The above commit adds getCNAMErecords

2023-07-06 13:40 UTC, SpookyKipper commented
Adds
`createCNAMErecord($source, $domain, $dest)`
`deleteCNAMErecord($source)`

2023-07-07 07:43 UTC, SpookyKipper commented
Adds full controls of MX and SPF records

2023-07-22 23:51 UTC, merged